// examples/11.1.0/docs/angular/demo/src/data-grid/data-grid.component.ts
import { Component, ViewEncapsulation } from "@angular/core";
import { getData } from "./utils/constants";
import { starsRenderer } from "./renderers/stars";
import { progressBarRenderer } from "./renderers/progressBar";

import {
  alignHeaders,
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "./utils/hooks-callbacks";

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: "data-grid",
  templateUrl: "./data-grid.component.html",
  styleUrls: ["./data-grid.scss"]
})
export class DataGridComponent {
  dataset = getData();
  alignHeaders = alignHeaders;
  drawCheckboxInRowHeaders = drawCheckboxInRowHeaders;
  addClassesToRows = addClassesToRows;
  changeCheckboxCell = changeCheckboxCell;
  progressBarRenderer = progressBarRenderer;
  starsRenderer = starsRenderer;
  colHeaders = [
    "Company name",
    "Country",
    "Name",
    "Sell date",
    "Order ID",
    "In stock",
    "Qty",
    "Progress",
    "Rating"
  ];
  hiddenColumns = {
    indicators: true
  };
  licenseKey = "non-commercial-and-evaluation";
}

<div>
  <hot-table
    class="hot"
    [data]="dataset"
    height="450"
    [colWidths]="[140, 126, 192, 100, 100, 90, 90, 110, 97]"
    [afterGetColHeader]="alignHeaders"
    [colHeaders]="colHeaders"
    [rowHeaders]="true"
    [dropdownMenu]="true"
    [hiddenColumns]="hiddenColumns"
    [contextMenu]="true"
    [multiColumnSorting]="true"
    [filters]="true"
    [afterOnCellMouseDown]="changeCheckboxCell"
    [afterGetColHeader]="alignHeaders"
    [afterGetRowHeader]="drawCheckboxInRowHeaders"
    [beforeRenderer]="addClassesToRows"
    licenseKey="non-commercial-and-evaluation"
  >
    <hot-column data="1"></hot-column>
    <hot-column data="2"></hot-column>
    <hot-column data="3"></hot-column>
    <hot-column data="4" type="date" [allowInvalid]="false"></hot-column>
    <hot-column data="5"></hot-column>
    <hot-column data="6" type="checkbox" className="htCenter"></hot-column>
    <hot-column data="7" type="numeric"></hot-column>
    <hot-column
      data="8"
      [renderer]="progressBarRenderer"
      [readOnly]="true"
      className="htMiddle"
    ></hot-column>
    <hot-column
      data="9"
      [renderer]="starsRenderer"
      [readOnly]="true"
      className="star htCenter"
    ></hot-column>
  </hot-table>
</div>

// examples/next/visual-tests/react/demo/src/DataGrid.tsx
import "@handsontable/pikaday/css/pikaday.css";
import "./styles.css";
import { HotTable, HotColumn } from "@handsontable/react";
import { data } from "./constants";
import { ProgressBarRenderer } from "./renderers/ProgressBar";
import { StarsRenderer } from "./renderers/Stars";

import {
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell,
  alignHeaders
} from "./hooksCallbacks";

import "handsontable/dist/handsontable.css";

const DataGrid = () => {
  return (
    <HotTable
      data={data}
      height={450}
      colWidths={[140, 192, 100, 90, 90, 110, 97, 100, 126]}
      colHeaders={[
        "Company name",
        "Name",
        "Sell date",
        "In stock",
        "Qty",
        "Progress",
        "Rating",
        "Order ID",
        "Country"
      ]}
      dropdownMenu={true}
      hiddenColumns={{
        indicators: true
      }}
      contextMenu={true}
      multiColumnSorting={true}
      filters={true}
      rowHeaders={true}
      afterGetColHeader={alignHeaders}
      beforeRenderer={addClassesToRows}
      afterGetRowHeader={drawCheckboxInRowHeaders}
      afterOnCellMouseDown={changeCheckboxCell}
      mergeCells={true}
      manualRowMove={true}
      navigableHeaders={true}
      licenseKey="non-commercial-and-evaluation"
    >
      <HotColumn data={1} />
      <HotColumn data={3} />
      <HotColumn data={4} type="date" allowInvalid={false} />
      <HotColumn data={6} type="checkbox" className="htCenter" />
      <HotColumn data={7} type="numeric" />
      <HotColumn data={8} readOnly={true} className="htMiddle">
        <ProgressBarRenderer hot-renderer />
      </HotColumn>
      <HotColumn data={9} readOnly={true} className="htCenter">
        <StarsRenderer hot-renderer />
      </HotColumn>
      <HotColumn data={5} />
      <HotColumn data={2} />
    </HotTable>
  );
}

export default DataGrid;
