// docs/content/guides/getting-started/grid-size/angular/example.js
/* file: app.component.ts */
import { Component, ViewChild } from '@angular/core';
import {
  GridSettings,
  HotTableComponent,
} from '@handsontable/angular-wrapper';

@Component({
  selector: 'example-grid-size',
  standalone: false,
  template: `<div class="controls">
      <button
        id="triggerBtn"
        class="button button--primary"
        (click)="btnClick()"
      >
        {{ isContainerExpanded ? 'Collapse container' : 'Expand container' }}
      </button>
    </div>
    <div class="ht-theme-main" [style.height.px]="currentHeight">
      <hot-table [data]="data" [settings]="gridSettings" />
    </div>`,
})
export class ExampleGridSizeComponent {
  @ViewChild(HotTableComponent, { static: false })
  readonly hotTable!: HotTableComponent;

  // generate an array of arrays with dummy data
  readonly data = new Array(100) // number of rows
    .fill(null)
    .map((_, row) =>
      new Array(50) // number of columns
        .fill(null)
        .map((_, column) => `${row}, ${column}`)
    );

  isContainerExpanded = false;
  currentHeight = 157;

  readonly gridSettings: GridSettings ={
    rowHeaders: true,
    colHeaders: true,
    width: '100%',
    height: '100%',
    colWidths: 100,
    autoWrapRow: true,
    autoWrapCol: true
  };

  btnClick(): void {
    this.isContainerExpanded = !this.isContainerExpanded;
    this.currentHeight = this.isContainerExpanded ? 410 : 157;

    this.hotTable?.hotInstance?.refreshDimensions();
  }
}
/* end-file */


/* file: app.module.ts */
import { NgModule, ApplicationConfig } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { registerAllModules } from 'handsontable/registry';
import { HOT_GLOBAL_CONFIG, HotConfig, HotTableModule } from '@handsontable/angular-wrapper';
import { CommonModule } from '@angular/common';
import { NON_COMMERCIAL_LICENSE } from '@handsontable/angular-wrapper';

/* start:skip-in-compilation */
import { ExampleGridSizeComponent } from './app.component';
/* end:skip-in-compilation */

// register Handsontable's modules
registerAllModules();

export const appConfig: ApplicationConfig = {
  providers: [
    {
      provide: HOT_GLOBAL_CONFIG,
      useValue: {
        themeName: 'ht-theme-main',
        license: NON_COMMERCIAL_LICENSE,
      } as HotConfig
    }
  ],
};

@NgModule({
  imports: [ BrowserModule, HotTableModule, CommonModule ],
  declarations: [ ExampleGridSizeComponent ],
  providers: [...appConfig.providers],
  bootstrap: [ ExampleGridSizeComponent ]
})

export class AppModule { }
/* end-file */

// docs/content/guides/getting-started/grid-size/react/example.tsx
import { useRef, useState, useEffect } from 'react';
import { HotTable, HotTableRef } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';
import 'handsontable/styles/handsontable.css';
import 'handsontable/styles/ht-theme-main.css';

// register Handsontable's modules
registerAllModules();

// generate an array of arrays with dummy data
const data = new Array(100) // number of rows
  .fill(null)
  .map((_, row) =>
    new Array(50) // number of columns
      .fill(null)
      .map((_, column) => `${row}, ${column}`)
  );

const ExampleComponent = () => {
  const [isContainerExpanded, setIsContainerExpanded] = useState(false);
  const hotRef = useRef<HotTableRef>(null);

  const triggerBtnClickCallback = () => {
    setIsContainerExpanded(!isContainerExpanded);
  };

  useEffect(() => {
    // simulate layout change outside of React lifecycle
    // @ts-ignore
    document.getElementById('exampleParent').style.height = isContainerExpanded ? '410px' : '157px';
    hotRef.current?.hotInstance?.refreshDimensions();
  });

  return (
    <>
      <div className="controls">
        <button id="triggerBtn" className="button button--primary" onClick={() => triggerBtnClickCallback()}>
          {isContainerExpanded ? 'Collapse container' : 'Expand container'}
        </button>
      </div>
      <div id="exampleParent" className="exampleParent">
        <HotTable
          themeName="ht-theme-main"
          data={data}
          rowHeaders={true}
          colHeaders={true}
          width="100%"
          height="100%"
          colWidths={100}
          autoWrapRow={true}
          autoWrapCol={true}
          licenseKey="non-commercial-and-evaluation"
          ref={hotRef}
        />
      </div>
    </>
  );
};

export default ExampleComponent;
