// examples/prs/angular/src/data-grid/data-grid.component.ts
import { Component, ViewEncapsulation } from "@angular/core";
import { getData } from "./utils/data";

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: "data-grid",
  templateUrl: "./data-grid.component.html",
  styleUrls: ["./data-grid.scss"],
})
export class DataGridComponent {
  dataset = getData();
   colHeaders = [
    "ID",
    "Item Name",
    "Item No.",
    "Lead Engineer",
    "Cost",
    "In Stock",
    "Category",
    "Item Quality",
    "Origin",
    "Quantity",
    "Value Stock",
    "Repairable",
    "Supplier Name",
    "Restock Date",
    "Operational Status",
  ];
  hiddenColumns = {
    columns: [0, 2], 
    indicators: true,
  };
  licenseKey = "non-commercial-and-evaluation";
}

<div>
  <hot-table
    class="hot"
    [data]="dataset"
    height="340"
    width="800"
    [colHeaders]="colHeaders"
    [rowHeaders]="true"
    [dropdownMenu]="true"
    [hiddenColumns]="hiddenColumns"
    [contextMenu]="true"
    [multiColumnSorting]="true"
    [filters]="true"
    [autoWrapRow]="true"
    [autoWrapCol]="true"
    headerClassName="htLeft"
    [beforeRenderer]="addClassesToRows"
    licenseKey="non-commercial-and-evaluation"
  >
    <hot-column data="id" type="numeric" [width]="150"></hot-column>
    <hot-column
      data="itemName"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
      [width]="150"
    ></hot-column>
    <hot-column
      data="itemNo"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
      [width]="150"
    ></hot-column>
    <hot-column
      data="leadEngineer"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="cost"
      type="numeric"
      headerClassName="htRight"
      className="htRight"
    ></hot-column>
    <hot-column
      data="inStock"
      type="checkbox"
      className="htCenter"
      headerClassName="htCenter"
    ></hot-column>
    <hot-column
      data="category"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="itemQuality"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="origin"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="quantity"
      type="numeric"
      headerClassName="htRight"
      className="htRight"
    ></hot-column>
    <hot-column
      data="valueStock"
      type="numeric"
      headerClassName="htRight"
      className="htRight"
    ></hot-column>
    <hot-column
      data="repairable"
      type="checkbox"
      className="htCenter"
      headerClassName="htCenter"
    ></hot-column>
    <hot-column
      data="supplierName"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="restockDate"
      type="date"
      [allowInvalid]="false"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
    <hot-column
      data="operationalStatus"
      type="text"
      headerClassName="htLeft"
      className="htLeft"
    ></hot-column>
  </hot-table>
</div>

// examples/prs/vue/src/components/DataGrid.vue
<template>
  <div id="example">
    <hot-table ref="hotTableComponent" :data="data" :settings="hotSettings"></hot-table>
  </div>
</template>

<script lang="ts">
import { HotTable } from "@handsontable/vue";
import { registerAllModules } from "handsontable/registry";

import { getData } from "../utils/data";

registerAllModules();

export default {
  name: "DataGrid",
  data: function () {
    return {
      hotSettings: {
        colHeaders: [
          "ID",
          "Item Name",
          "Item No.",
          "Lead Engineer",
          "Cost",
          "In Stock",
          "Category",
          "Item Quality",
          "Origin",
          "Quantity",
          "Value Stock",
          "Repairable",
          "Supplier Name",
          "Restock Date",
          "Operational Status",
        ],
        rowHeaders: true,
        height: 340,
        width: 800,
        autoWrapRow: true,
        autoWrapCol: true,
        dropdownMenu: true,
        filters: true,
        multiColumnSorting: true,
        hiddenColumns: {
          columns: [0, 2], // Hides the ID and Item No. columns
          indicators: true,
        },
        columns: [
          { data: "id", type: "numeric", width: 150 },
          {
            data: "itemName",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          },
          {
            data: "itemNo",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          }, // Hidden column
          {
            data: "leadEngineer",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          },
          {
            data: "cost",
            type: "numeric",
            numericFormat: { pattern: "$0 0" },
            headerClassName: "htRight",
            className: "htRight",
            width: 150,
          },
          {
            data: "inStock",
            type: "checkbox",
            headerClassName: "htCenter",
            className: "htCenter",
            width: 100,
          },
          {
            data: "category",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          },
          {
            data: "itemQuality",
            type: "numeric",
            numericFormat: { pattern: "0%" },
            headerClassName: "htRight",
            className: "htRight",
            width: 150,
          },
          {
            data: "origin",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          },
          {
            data: "quantity",
            type: "numeric",
            headerClassName: "htRight",
            className: "htRight",
            width: 150,
          },
          {
            data: "valueStock",
            type: "numeric",
            numericFormat: { pattern: "$0 0" },
            headerClassName: "htRight",
            className: "htRight",
            width: 150,
          },
          {
            data: "repairable",
            type: "checkbox",
            headerClassName: "htCenter",
            className: "htCenter",
            width: 100,
          },
          {
            data: "supplierName",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 150,
          },
          {
            data: "restockDate",
            type: "date",
            dateFormat: "YYYY-MM-DD",
            headerClassName: "htRight",
            className: "htRight",
            width: 150,
          },
          {
            data: "operationalStatus",
            type: "text",
            headerClassName: "htLeft",
            className: "htLeft",
            width: 180,
          },
        ],
        licenseKey: "non-commercial-and-evaluation",
      },
      data: getData(),
    };
  },
  components: {
    HotTable,
  },
};
</script>
