// docs/content/guides/columns/column-filter/vue/exampleSaveRestoreFilters.vue
<script setup lang="ts">
import { ref, useTemplateRef } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';
import type { ColumnConditions } from 'handsontable/plugins/filters';

// register Handsontable's modules
registerAllModules();

const hotTableRef = useTemplateRef<InstanceType<typeof HotTable>>('hotTableRef');
let savedConditions: ColumnConditions[] = [];

const applySampleFilter = () => {
  const filters = hotTableRef.value?.hotInstance?.getPlugin('filters');

  filters?.clearConditions();
  // filter the 'Price' column (column at index 2) for items over $200
  filters?.addCondition(2, 'gt', [200]);
  filters?.filter();
};

const saveFilters = () => {
  const filters = hotTableRef.value?.hotInstance?.getPlugin('filters');

  // `exportConditions()` returns the current conditions, keyed by physical column index
  savedConditions = filters?.exportConditions() ?? [];
};

const clearFilters = () => {
  const filters = hotTableRef.value?.hotInstance?.getPlugin('filters');

  filters?.clearConditions();
  filters?.filter();
};

const restoreFilters = () => {
  const filters = hotTableRef.value?.hotInstance?.getPlugin('filters');

  // `importConditions()` expects the same physical-column-indexed structure
  filters?.importConditions(savedConditions);
  filters?.filter();
};

const hotSettings = ref<GridSettings>({
  data: [
    {
      brand: 'Jetpulse',
      model: 'Racing Socks',
      price: 30,
      sellDate: '2023-10-11',
      sellTime: '01:23',
      inStock: false,
    },
    {
      brand: 'Gigabox',
      model: 'HL Mountain Frame',
      price: 1890.9,
      sellDate: '2023-05-03',
      sellTime: '11:27',
      inStock: false,
    },
    {
      brand: 'Camido',
      model: 'Cycling Cap',
      price: 130.1,
      sellDate: '2023-03-27',
      sellTime: '03:17',
      inStock: true,
    },
    {
      brand: 'Chatterpoint',
      model: 'Road Tire Tube',
      price: 59,
      sellDate: '2023-08-28',
      sellTime: '08:01',
      inStock: true,
    },
    {
      brand: 'Eidel',
      model: 'HL Road Tire',
      price: 279.99,
      sellDate: '2023-10-02',
      sellTime: '01:23',
      inStock: true,
    },
  ],
  columns: [
    {
      title: 'Brand',
      type: 'text',
      data: 'brand',
    },
    {
      title: 'Model',
      type: 'text',
      data: 'model',
    },
    {
      title: 'Price',
      type: 'numeric',
      data: 'price',
      locale: 'en-US',
      numericFormat: {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 2,
      },
    },
    {
      title: 'Date',
      type: 'intl-date',
      data: 'sellDate',
      locale: 'en-US',
      dateFormat: { month: 'short', day: 'numeric', year: 'numeric' },
      className: 'htRight',
    },
    {
      title: 'Time',
      type: 'intl-time',
      data: 'sellTime',
      locale: 'en-US',
      timeFormat: { hour: '2-digit', minute: '2-digit', hour12: true },
      className: 'htRight',
    },
    {
      title: 'In stock',
      type: 'checkbox',
      data: 'inStock',
      className: 'htCenter',
    },
  ],
  // enable filtering
  filters: true,
  // enable the column menu
  dropdownMenu: true,
  height: 'auto',
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
});
</script>

<template>
  <div id="exampleSaveRestoreFilters">
    <div class="example-controls-container">
      <div class="controls">
        <button @click="applySampleFilter">Filter: price &gt; $200</button>
        <button @click="saveFilters">Save filter settings</button>
        <button @click="clearFilters">Clear filters</button>
        <button @click="restoreFilters">Restore filter settings</button>
      </div>
    </div>
    <HotTable ref="hotTableRef" :settings="hotSettings" />
  </div>
</template>

// docs/content/guides/columns/column-filter/react/exampleSaveRestoreFilters.jsx
import { useRef } from 'react';
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

const ExampleComponent = () => {
  const hotTableComponentRef = useRef(null);
  const savedConditions = useRef([]);

  const applySampleFilter = () => {
    const filters = hotTableComponentRef.current?.hotInstance?.getPlugin('filters');

    filters?.clearConditions();
    // filter the 'Price' column (column at index 2) for items over $200
    filters?.addCondition(2, 'gt', [200]);
    filters?.filter();
  };

  const saveFilters = () => {
    const filters = hotTableComponentRef.current?.hotInstance?.getPlugin('filters');

    // `exportConditions()` returns the current conditions, keyed by physical column index
    savedConditions.current = filters?.exportConditions() ?? [];
  };

  const clearFilters = () => {
    const filters = hotTableComponentRef.current?.hotInstance?.getPlugin('filters');

    filters?.clearConditions();
    filters?.filter();
  };

  const restoreFilters = () => {
    const filters = hotTableComponentRef.current?.hotInstance?.getPlugin('filters');

    // `importConditions()` expects the same physical-column-indexed structure
    filters?.importConditions(savedConditions.current);
    filters?.filter();
  };

  return (
    <>
      <div className="example-controls-container">
        <div className="controls">
          <button onClick={applySampleFilter}>Filter: price &gt; $200</button>
          <button onClick={saveFilters}>Save filter settings</button>
          <button onClick={clearFilters}>Clear filters</button>
          <button onClick={restoreFilters}>Restore filter settings</button>
        </div>
      </div>
      <HotTable
        ref={hotTableComponentRef}
        data={[
          {
            brand: 'Jetpulse',
            model: 'Racing Socks',
            price: 30,
            sellDate: '2023-10-11',
            sellTime: '01:23',
            inStock: false,
          },
          {
            brand: 'Gigabox',
            model: 'HL Mountain Frame',
            price: 1890.9,
            sellDate: '2023-05-03',
            sellTime: '11:27',
            inStock: false,
          },
          {
            brand: 'Camido',
            model: 'Cycling Cap',
            price: 130.1,
            sellDate: '2023-03-27',
            sellTime: '03:17',
            inStock: true,
          },
          {
            brand: 'Chatterpoint',
            model: 'Road Tire Tube',
            price: 59,
            sellDate: '2023-08-28',
            sellTime: '08:01',
            inStock: true,
          },
          {
            brand: 'Eidel',
            model: 'HL Road Tire',
            price: 279.99,
            sellDate: '2023-10-02',
            sellTime: '01:23',
            inStock: true,
          },
        ]}
        columns={[
          {
            title: 'Brand',
            type: 'text',
            data: 'brand',
          },
          {
            title: 'Model',
            type: 'text',
            data: 'model',
          },
          {
            title: 'Price',
            type: 'numeric',
            data: 'price',
            locale: 'en-US',
            numericFormat: {
              style: 'currency',
              currency: 'USD',
              minimumFractionDigits: 2,
            },
          },
          {
            title: 'Date',
            type: 'intl-date',
            data: 'sellDate',
            locale: 'en-US',
            dateFormat: { month: 'short', day: 'numeric', year: 'numeric' },
            className: 'htRight',
          },
          {
            title: 'Time',
            type: 'intl-time',
            data: 'sellTime',
            locale: 'en-US',
            timeFormat: { hour: '2-digit', minute: '2-digit', hour12: true },
            className: 'htRight',
          },
          {
            title: 'In stock',
            type: 'checkbox',
            data: 'inStock',
            className: 'htCenter',
          },
        ]}
        // enable filtering
        filters={true}
        // enable the column menu
        dropdownMenu={true}
        height="auto"
        autoWrapRow={true}
        autoWrapCol={true}
        licenseKey="non-commercial-and-evaluation"
      />
    </>
  );
};

export default ExampleComponent;
