// docs/content/guides/columns/column-filter/react/exampleServerSideFilter.tsx
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

const data = [
  {
    brand: 'Jetpulse',
    model: 'Racing Socks',
    price: 30,
    sellDate: '2023-10-11',
    sellTime: '01:23',
    inStock: false,
  },
  {
    brand: 'Gigabox',
    model: 'HL Mountain Frame',
    price: 1890.9,
    sellDate: '2023-05-03',
    sellTime: '11:27',
    inStock: false,
  },
  {
    brand: 'Camido',
    model: 'Cycling Cap',
    price: 130.1,
    sellDate: '2023-03-27',
    sellTime: '03:17',
    inStock: true,
  },
  {
    brand: 'Chatterpoint',
    model: 'Road Tire Tube',
    price: 59,
    sellDate: '2023-08-28',
    sellTime: '08:01',
    inStock: true,
  },
  {
    brand: 'Eidel',
    model: 'HL Road Tire',
    price: 279.99,
    sellDate: '2023-10-02',
    sellTime: '01:23',
    inStock: true,
  },
];

const ExampleComponent = () => {
  return (
    <HotTable
      data={data}
      columns={[
        {
          title: 'Brand',
          type: 'text',
          data: 'brand',
        },
        {
          title: 'Model',
          type: 'text',
          data: 'model',
        },
        {
          title: 'Price',
          type: 'numeric',
          data: 'price',
          locale: 'en-US',
          numericFormat: {
            style: 'currency',
            currency: 'USD',
            minimumFractionDigits: 2,
          },
        },
        {
          title: 'Date',
          type: 'intl-date',
          data: 'sellDate',
          locale: 'en-US',
          dateFormat: { month: 'short', day: 'numeric', year: 'numeric' },
          className: 'htRight',
        },
        {
          title: 'Time',
          type: 'intl-time',
          data: 'sellTime',
          locale: 'en-US',
          timeFormat: { hour: '2-digit', minute: '2-digit', hour12: true },
          className: 'htRight',
        },
        {
          title: 'In stock',
          type: 'checkbox',
          data: 'inStock',
          className: 'htCenter',
        },
      ]}
      // enable filtering
      filters={true}
      // enable the column menu
      dropdownMenu={true}
      height="auto"
      // `beforeFilter()` is a Handsontable hook
      // it's fired after Handsontable gathers information about the filters, but before the filters are applied
      beforeFilter={function (conditionsStack) {
        // gather information about the filters
        console.log(`The amount of filters: ${conditionsStack.length}`);

        // when the filters are cleared, the conditions stack is empty
        const [lastChanged] = conditionsStack;

        if (lastChanged) {
          console.log(`The last changed column index: ${lastChanged.column}`);
          console.log(`The amount of filters added to this column: ${lastChanged.conditions.length}`);
          // the list of filter conditions
          console.log(lastChanged.conditions);
        }

        // return `false` to disable filtering on the client side
        return false;
      }}
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation"
    />
  );
};

export default ExampleComponent;

// docs/content/guides/columns/column-filter/vue/exampleServerSideFilter.vue
<script setup lang="ts">
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';

// register Handsontable's modules
registerAllModules();

const hotSettings = ref<GridSettings>({
  data: [
    {
      brand: 'Jetpulse',
      model: 'Racing Socks',
      price: 30,
      sellDate: '2023-10-11',
      sellTime: '01:23',
      inStock: false,
    },
    {
      brand: 'Gigabox',
      model: 'HL Mountain Frame',
      price: 1890.9,
      sellDate: '2023-05-03',
      sellTime: '11:27',
      inStock: false,
    },
    {
      brand: 'Camido',
      model: 'Cycling Cap',
      price: 130.1,
      sellDate: '2023-03-27',
      sellTime: '03:17',
      inStock: true,
    },
    {
      brand: 'Chatterpoint',
      model: 'Road Tire Tube',
      price: 59,
      sellDate: '2023-08-28',
      sellTime: '08:01',
      inStock: true,
    },
    {
      brand: 'Eidel',
      model: 'HL Road Tire',
      price: 279.99,
      sellDate: '2023-10-02',
      sellTime: '01:23',
      inStock: true,
    },
  ],
  columns: [
    {
      title: 'Brand',
      type: 'text',
      data: 'brand',
    },
    {
      title: 'Model',
      type: 'text',
      data: 'model',
    },
    {
      title: 'Price',
      type: 'numeric',
      data: 'price',
      locale: 'en-US',
      numericFormat: {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 2,
      },
    },
    {
      title: 'Date',
      type: 'intl-date',
      data: 'sellDate',
      locale: 'en-US',
      dateFormat: { month: 'short', day: 'numeric', year: 'numeric' },
      className: 'htRight',
    },
    {
      title: 'Time',
      type: 'intl-time',
      data: 'sellTime',
      locale: 'en-US',
      timeFormat: { hour: '2-digit', minute: '2-digit', hour12: true },
      className: 'htRight',
    },
    {
      title: 'In stock',
      type: 'checkbox',
      data: 'inStock',
      className: 'htCenter',
    },
  ],
  // enable filtering
  filters: true,
  // enable the column menu
  dropdownMenu: true,
  height: 'auto',
  // `beforeFilter()` is a Handsontable hook
  // it's fired after Handsontable gathers information about the filters, but before the filters are applied
  beforeFilter(conditionsStack) {
    // gather information about the filters
    console.log(`The amount of filters: ${conditionsStack.length}`);

    // when the filters are cleared, the conditions stack is empty
    const [lastChanged] = conditionsStack;

    if (lastChanged) {
      console.log(`The last changed column index: ${lastChanged.column}`);
      console.log(`The amount of filters added to this column: ${lastChanged.conditions.length}`);
      // the list of filter conditions
      console.log(lastChanged.conditions);
    }

    // return `false` to disable filtering on the client side
    return false;
  },
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
});
</script>

<template>
  <div id="exampleServerSideFilter">
    <HotTable :settings="hotSettings" />
  </div>
</template>
