// examples/next/docs/vue/basic-example/src/components/HotTable.vue
<template>
  <hot-table :settings="hotSettings"></hot-table>
</template>

<script>
import { HotTable } from "@handsontable/vue";
import Handsontable from "handsontable";

export default {
  data: function () {
    return {
      hotSettings: {
        data: Handsontable.helper.createSpreadsheetData(6, 10),
        colHeaders: true,
        licenseKey: 'non-commercial-and-evaluation'
      },
    };
  },
  components: {
    HotTable,
  },
};
</script>

<style>
@import "~handsontable/dist/handsontable.full.css";
</style>

// examples/next/docs/angular/custom-context-menu/src/app/hot-table/hot-table.component.ts
import { Component, OnInit } from '@angular/core';
import Handsontable from 'handsontable';

@Component({
  selector: 'app-hot-table',
  template: '<hot-table [settings]="hotSettings"></hot-table>'
})
export class HotTableComponent implements OnInit {

  hotSettings: Handsontable.GridSettings = {
    data: Handsontable.helper.createSpreadsheetData(5, 5),
    colHeaders: true,
    contextMenu: {
      items: {
        'row_above': {
          name: 'Insert row above this one (custom name)'
        },
        'row_below': {},
        'separator': Handsontable.plugins.ContextMenu.SEPARATOR,
        'clear_custom': {
          name: 'Clear all cells (custom)',
          callback: function() {
            this.clear();
          }
        }
      }
    },
    licenseKey: 'non-commercial-and-evaluation'
  }

  ngOnInit(): void {
  }

}
