// docs/content/guides/columns/column-summary/react/example11.jsx
import { useRef } from 'react';
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

const data = [[0, 1, 2], ['3c', '4b', 5], [], []];

const ExampleComponent = () => {
  const hotRef = useRef(null);

  const throwErrors = () => {
    hotRef.current?.hotInstance?.updateSettings({
      columnSummary: [
        {
          type: 'sum',
          destinationRow: 0,
          destinationColumn: 0,
          reversedRowCoords: true,
          suppressDataTypeErrors: false,
        },
        {
          type: 'sum',
          destinationRow: 0,
          destinationColumn: 1,
          reversedRowCoords: true,
          suppressDataTypeErrors: false,
        },
      ],
    });
  };

  return (
    <>
      <div className="example-controls-container">
        <div className="controls">
          <button className="button button--primary" onClick={throwErrors}>
            Throw data type errors
          </button>
        </div>
      </div>
      <HotTable
        ref={hotRef}
        autoWrapRow={true}
        autoWrapCol={true}
        licenseKey="non-commercial-and-evaluation"
        data={data}
        colHeaders={true}
        rowHeaders={true}
        columnSummary={[
          {
            type: 'sum',
            destinationRow: 0,
            destinationColumn: 0,
            reversedRowCoords: true,
          },
          {
            type: 'sum',
            destinationRow: 0,
            destinationColumn: 1,
            reversedRowCoords: true,
          },
        ]}
        height="auto"
      />
    </>
  );
};

export default ExampleComponent;

// docs/content/guides/columns/column-summary/vue/example11.vue
<script setup lang="ts">
import { ref, useTemplateRef } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';

// register Handsontable's modules
registerAllModules();

const hotRef = useTemplateRef<InstanceType<typeof HotTable>>('hotRef');

const hotSettings = ref<GridSettings>({
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
  data: [[0, 1, 2], [3, 4, 5], [], []],
  colHeaders: true,
  rowHeaders: true,
  columnSummary: [
    {
      type: 'sum',
      destinationRow: 0,
      destinationColumn: 0,
      reversedRowCoords: true,
    },
    {
      type: 'sum',
      destinationRow: 0,
      destinationColumn: 1,
      reversedRowCoords: true,
    },
  ],
  height: 'auto',
});

function throwErrors() {
  hotRef.value?.hotInstance?.updateSettings({
    columnSummary: [
      {
        type: 'sum',
        destinationRow: 0,
        destinationColumn: 0,
        reversedRowCoords: true,
        suppressDataTypeErrors: false,
      },
      {
        type: 'sum',
        destinationRow: 0,
        destinationColumn: 1,
        reversedRowCoords: true,
        suppressDataTypeErrors: false,
      },
    ],
  });
}
</script>

<template>
  <div id="example11">
    <div class="example-controls-container">
      <div class="controls">
        <button class="button button--primary" @click="throwErrors">
          Throw data type errors
        </button>
      </div>
    </div>
    <HotTable ref="hotRef" :settings="hotSettings" />
  </div>
</template>
