// examples/next/docs/vue/basic-example/src/components/HotTable.vue
<template>
  <hot-table :settings="hotSettings"></hot-table>
</template>

<script>
import { HotTable } from "@handsontable/vue";
import Handsontable from "handsontable";

export default {
  data: function () {
    return {
      hotSettings: {
        data: Handsontable.helper.createSpreadsheetData(6, 10),
        colHeaders: true,
        licenseKey: 'non-commercial-and-evaluation'
      },
    };
  },
  components: {
    HotTable,
  },
};
</script>

<style>
@import "~handsontable/dist/handsontable.full.css";
</style>

// examples/templates/angular/src/app/hot-table/hot-table.component.ts
import { Component, OnInit } from '@angular/core';
import type Handsontable from 'handsontable';

@Component({
  selector: 'app-hot-table',
  templateUrl: './hot-table.component.html',
  styleUrls: ['./hot-table.component.scss']
})
export class HotTableComponent implements OnInit {

  hotSettings: Handsontable.GridSettings = {
    data: [
        ['', 'Tesla', 'Volvo', 'Toyota', 'Ford'],
        ['2019', 10, 11, 12, 13],
        ['2020', 20, 11, 14, 13],
        ['2021', 30, 15, 12, 13]
    ],
    colHeaders: true,
    rowHeaders: true,
    licenseKey: 'non-commercial-and-evaluation'
  };

  ngOnInit(): void {
  }

}

<hot-table
  [settings]="hotSettings"
  ></hot-table>
