// examples/templates/vue/src/components/HotTable.vue
<template>
  <hot-table :settings="hotSettings"></hot-table>
</template>

<script>
import "handsontable/dist/handsontable.full.css";

import Handsontable from "handsontable";
import { HotTable } from "@handsontable/vue";
import Vue from "vue";

function getDebugInfo() {
  let debug = "Handsontable:";
  debug += ` v${Handsontable.version}`;
  debug += ` (${Handsontable.buildDate})`;
  debug += " Wrapper:";
  debug += ` v${HotTable.version}`;
  debug += " Vue:";
  debug += ` v${Vue.version}`;
  return debug;
}

console.log(getDebugInfo());

export default {
  data: function () {
    return {
      hotSettings: {
        data: [
          ["", "Ford", "Volvo", "Toyota", "Honda"],
          ["2016", 10, 11, 12, 13],
          ["2017", 20, 11, 14, 13],
          ["2018", 30, 15, 12, 13],
        ],
        colHeaders: true,
        rowHeaders: true,
        licenseKey: "non-commercial-and-evaluation",
      },
    };
  },
  components: {
    HotTable,
  },
};
</script>

// examples/templates/angular/src/app/hot-table/hot-table.component.ts
import { Component, OnInit } from '@angular/core';
import type Handsontable from 'handsontable';

@Component({
  selector: 'app-hot-table',
  templateUrl: './hot-table.component.html',
  styleUrls: ['./hot-table.component.scss']
})
export class HotTableComponent implements OnInit {

  hotSettings: Handsontable.GridSettings = {
    data: [
        ['', 'Tesla', 'Volvo', 'Toyota', 'Ford'],
        ['2019', 10, 11, 12, 13],
        ['2020', 20, 11, 14, 13],
        ['2021', 30, 15, 12, 13]
    ],
    colHeaders: true,
    rowHeaders: true,
    licenseKey: 'non-commercial-and-evaluation'
  };

  ngOnInit(): void {
  }

}

<hot-table
  [settings]="hotSettings"
  ></hot-table>
