// docs/content/guides/cell-features/clipboard/vue/example5.vue
<script setup lang="ts">
import Handsontable from 'handsontable/base';
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';

type CopyRange = { startRow: number; startCol: number; endRow: number; endCol: number };

registerAllModules();

const copiedComments = ref<(string | undefined)[][]>([]);

function collectComments(hot: Handsontable, coords: CopyRange[]): (string | undefined)[][] {
  const source = coords[0];
  const comments = hot.getPlugin('comments');
  const copied: (string | undefined)[][] = [];

  if (!source) {
    return copied;
  }

  for (let row = source.startRow; row <= source.endRow; row += 1) {
    const rowComments: (string | undefined)[] = [];

    for (let col = source.startCol; col <= source.endCol; col += 1) {
      rowComments.push(comments.getCommentAtCell(row, col));
    }

    copied.push(rowComments);
  }

  return copied;
}

const hotSettings = ref<GridSettings>({
  data: [
    ['Wireless mouse', 142, 'In stock'],
    ['USB-C cable', 67, 'In stock'],
    ['Mechanical keyboard', 0, 'Backordered'],
    ['Laptop stand', 38, 'In stock'],
    ['HDMI adapter', 210, 'In stock'],
  ],
  colHeaders: ['Product', 'Stock', 'Status'],
  rowHeaders: true,
  comments: true,
  cell: [
    { row: 0, col: 1, comment: { value: 'Counted during the July audit.' } },
    { row: 2, col: 1, comment: { value: 'Reorder request sent to Harbor Goods.' } },
    { row: 2, col: 2, comment: { value: 'Expected delivery is July 18.' } },
  ],
  afterCopy(this: Handsontable, _data, coords) {
    copiedComments.value = collectComments(this, coords as CopyRange[]);
  },
  afterPaste(this: Handsontable, _data, coords) {
    const target = (coords as CopyRange[])[0];
    const comments = this.getPlugin('comments');

    if (!target) {
      return;
    }

    this.batch(() => {
      copiedComments.value.forEach((rowComments, rowOffset) => {
        rowComments.forEach((comment, colOffset) => {
          const row = target.startRow + rowOffset;
          const col = target.startCol + colOffset;

          if (comment) {
            comments.setCommentAtCell(row, col, comment);
          } else {
            comments.removeCommentAtCell(row, col, false);
          }
        });
      });
    });

    this.render();
  },
  height: 'auto',
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
});
</script>

<template>
  <div id="example5">
    <HotTable :settings="hotSettings" />
  </div>
</template>

// docs/content/guides/cell-features/comments/react/example5.tsx
import Handsontable from 'handsontable/base';
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

const data = [
  ['Wireless mouse', 142],
  ['USB-C cable', 67],
  ['Mechanical keyboard', -5],
  ['Laptop stand', 38],
  ['HDMI adapter', 210],
];

const ExampleComponent = () => {
  return (
    <HotTable
      data={data}
      colHeaders={['Product', 'Stock']}
      rowHeaders={true}
      comments={true}
      columns={[
        {},
        {
          type: 'numeric',
          validator(value: any, callback: (valid: boolean) => void) {
            callback(Number.isInteger(value) && value >= 0);
          },
        },
      ]}
      // Attach a comment when a cell fails validation, and remove it once the cell is valid.
      afterValidate={function (this: Handsontable, isValid, value, row, prop) {
        const column = this.propToCol(prop);
        const comments = this.getPlugin('comments');

        if (!isValid) {
          comments.setCommentAtCell(row, column, `"${value}" is not valid. Enter a whole number of 0 or more.`);
        } else {
          comments.removeCommentAtCell(row, column);
        }
      }}
      // Validate every cell on load so the pre-existing invalid value is flagged right away.
      afterInit={function (this: Handsontable) {
        this.validateCells();
      }}
      height="auto"
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation"
    />
  );
};

export default ExampleComponent;
