// docs/content/guides/getting-started/grid-size/react/example.jsx
import { useRef, useState, useEffect } from 'react';
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

// generate an array of arrays with dummy data
const data = new Array(100) // number of rows
  .fill(null)
  .map((_, row) =>
    new Array(50) // number of columns
      .fill(null)
      .map((_, column) => `${row}, ${column}`)
  );

const ExampleComponent = () => {
  const [isContainerExpanded, setIsContainerExpanded] = useState(false);
  const hotRef = useRef(null);
  const triggerBtnClickCallback = () => {
    setIsContainerExpanded(!isContainerExpanded);
  };

  useEffect(() => {
    // simulate layout change outside of React lifecycle
    // @ts-ignore
    document.getElementById('exampleParent').style.height = isContainerExpanded ? '410px' : '157px';
    hotRef.current?.hotInstance?.refreshDimensions();
  });

  return (
    <>
      <div className="example-controls-container">
        <div className="controls">
          <button id="triggerBtn" className="button button--primary" onClick={() => triggerBtnClickCallback()}>
            {isContainerExpanded ? 'Collapse container' : 'Expand container'}
          </button>
        </div>
      </div>
      <div id="exampleParent" className="exampleParent">
        <HotTable
          data={data}
          rowHeaders={true}
          colHeaders={true}
          width="100%"
          height="100%"
          colWidths={100}
          autoWrapRow={true}
          autoWrapCol={true}
          licenseKey="non-commercial-and-evaluation"
          ref={hotRef}
        />
      </div>
    </>
  );
};

export default ExampleComponent;

// docs/content/guides/getting-started/grid-size/vue/example.vue
<script setup>
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';

registerAllModules();

const data = new Array(100)
  .fill(null)
  .map((_, row) =>
    new Array(50)
      .fill(null)
      .map((_, column) => `${row}, ${column}`)
  );

const isContainerExpanded = ref(false);
const hotRef = ref(null);

function triggerBtnClickCallback() {
  isContainerExpanded.value = !isContainerExpanded.value;
  const parent = document.getElementById('exampleParent');

  parent.style.height = isContainerExpanded.value ? '410px' : '157px';
  hotRef.value?.hotInstance?.refreshDimensions();
}

const hotSettings = ref({
  data,
  rowHeaders: true,
  colHeaders: true,
  width: '100%',
  height: '100%',
  colWidths: 100,
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
});
</script>

<template>
  <div id="example">
    <div class="example-controls-container">
      <div class="controls">
        <button id="triggerBtn" class="button button--primary" @click="triggerBtnClickCallback">
          {{ isContainerExpanded ? 'Collapse container' : 'Expand container' }}
        </button>
      </div>
    </div>
    <div id="exampleParent" class="exampleParent">
      <HotTable ref="hotRef" :settings="hotSettings" />
    </div>
  </div>
</template>

<style>
#exampleParent {
  height: 157px;
}

#exampleParent > div {
  height: 100%;
}
</style>
