// examples/next/docs/vue/basic-example/src/components/HotTable.vue
<template>
  <hot-table :settings="hotSettings"></hot-table>
</template>

<script>
import { HotTable } from "@handsontable/vue";
import Handsontable from "handsontable";

export default {
  data: function () {
    return {
      hotSettings: {
        data: Handsontable.helper.createSpreadsheetData(6, 10),
        colHeaders: true,
        licenseKey: 'non-commercial-and-evaluation'
      },
    };
  },
  components: {
    HotTable,
  },
};
</script>

<style>
@import "~handsontable/dist/handsontable.full.css";
</style>

// examples/next/docs/angular/custom-id/src/app/hot-table/hot-table.component.ts
import { Component, OnInit } from '@angular/core';
import type Handsontable from 'handsontable';

@Component({
  selector: 'app-hot-table',
  templateUrl: './hot-table.component.html',
  styleUrls: ['./hot-table.component.scss']
})
export class HotTableComponent implements OnInit {

  hotSettings: Handsontable.GridSettings = {
    startRows: 5,
    startCols: 5,
    colHeaders: true,
    stretchH: 'all',
    licenseKey: 'non-commercial-and-evaluation'
  };

  id = 'my-custom-id';

  ngOnInit(): void {
  }
}

<hot-table
  [settings]="hotSettings"
  [hotId]="id"
  ></hot-table>
