// examples/next/docs/react-wrapper/accessibility/src/App.tsx
import { HotTable, HotColumn } from "@handsontable/react-wrapper";
import { useState } from "react";

import { countries, data } from "./data";
import DemoOptions from "./DemoOptions";

import { registerAllModules } from 'handsontable/registry';

registerAllModules();

// Handsontable options
const hotOptions = {
  data,
  height: 464,
  colWidths: [140, 165, 100, 100, 100, 110, 178],
  colHeaders: [
    "Company name",
    "Product name",
    "Sell date",
    "In stock",
    "Qty",
    "Order ID",
    "Country",
  ],
  dropdownMenu: true,
  hiddenColumns: {
    indicators: true,
  },
  multiColumnSorting: true,
  filters: true,
  rowHeaders: true,
  manualRowMove: true,
  headerClassName: "htLeft",
  licenseKey: "non-commercial-and-evaluation",
};

export interface ToggleableOptions {
  tabNavigation: boolean;
  navigableHeaders: boolean;
  renderAllRows: boolean;
  enterBeginsEditing: boolean;
  autoWrapRow: boolean;
  autoWrapCol: boolean;
  enterMoves: { col: number; row: number };
}

function App() {
  const [toggleableOptions, setToggleableOptions] = useState<ToggleableOptions>(
    {
      tabNavigation: true,
      navigableHeaders: true,
      renderAllRows: false,
      enterBeginsEditing: true,
      autoWrapRow: true,
      autoWrapCol: true,
      enterMoves: { col: 0, row: 1 },
    }
  );

  return (
    <>
      {/* DemoOptions component for changing Handsontable options */}
      <DemoOptions
        changeToggleOptions={setToggleableOptions}
        {...toggleableOptions}
      />

      <input
        className="placeholder-input"
        type="text"
        placeholder="Focusable text input"
      />

      {/* Handsontable component with dynamic options */}
      <HotTable
        // Handsontable needs to reload when changing virtualization
        // by changing the key, we force the component to reload
        key={String(toggleableOptions.renderAllRows)}
        {...hotOptions}
        // Pass in the options which can change for demo
        {...toggleableOptions}
      >
        {/* Define HotColumns for the data */}
        <HotColumn data="companyName" type="text" />
        <HotColumn data="productName" type="text" />
        <HotColumn
          data="sellDate"
          dateFormat={{ day: '2-digit', month: '2-digit', year: 'numeric' }}
          locale="en-GB"
          correctFormat
          type="date"
          allowInvalid={false}
        />
        <HotColumn data="inStock" type="checkbox" className="htCenter" headerClassName="htCenter" />
        <HotColumn data="qty" type="numeric" headerClassName="htRight" />
        <HotColumn data="orderId" type="text" />
        <HotColumn data="country" type="dropdown" source={countries} />
      </HotTable>
      <input
        className="placeholder-input"
        type="text"
        placeholder="Focusable text input"
      />
    </>
  );
}

export default App;

// examples/next/docs/angular-wrapper/demo/src/app/app.component.ts
import { HotTableModule, GridSettings } from "@handsontable/angular-wrapper";
import { Component } from "@angular/core";
import { data } from "./constants";
import { PredefinedMenuItemKey } from "handsontable/plugins/contextMenu";
import { addClassesToRows } from "./utils/add-classes-to-rows.function";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.scss",
  standalone: true,
  imports: [HotTableModule],
})
export class AppComponent {
  readonly initialData = data;
  readonly gridSettings: GridSettings = {
    height: 450,
    colWidths: [180, 220, 140, 120, 120, 120, 140],
    colHeaders: [
      "Company Name",
      "Name",
      "Sell date",
      "In stock",
      "Quantity",
      "Order ID",
      "Country",
    ],
    contextMenu: [
      "cut",
      "copy",
      "---------",
      "row_above",
      "row_below",
      "remove_row",
      "---------",
      "alignment",
      "make_read_only",
      "clear_column",
    ] as PredefinedMenuItemKey[],
    dropdownMenu: true,
    hiddenColumns: {
      indicators: true,
    },
    multiColumnSorting: true,
    filters: true,
    rowHeaders: true,
    headerClassName: "htLeft",
    beforeRenderer: addClassesToRows,
    manualRowMove: true,
    autoWrapRow: true,
    autoWrapCol: true,
    autoRowSize: true,
    manualRowResize: true,
    manualColumnResize: true,
    navigableHeaders: true,
    imeFastEdit: true,
    columns: [
      { data: 1 },
      { data: 3 },
      {
        data: 4,
        type: "date",
        allowInvalid: false,
        dateFormat: { day: "2-digit", month: "2-digit", year: "numeric" },
        locale: "en-GB",
      },
      { data: 6, type: "checkbox", className: "htCenter" },
      { data: 7, type: "numeric" },
      { data: 5 },
      { data: 2 },
    ],
  };
}

<div>
  <hot-table [data]="initialData" [settings]="gridSettings"></hot-table>
</div>
