// examples/next/docs/react/accessibility/src/App.tsx
import "handsontable/dist/handsontable.min.css";
import { HotTable, HotColumn } from "@handsontable/react";
import { useState } from "react";
import { ProgressBarRenderer } from "./components/ProgressBarRenderer";
import { StarsRenderer } from "./components/StarsRenderer";

import { countries, data } from "./data";
import DemoOptions from "./components/DemoOptions";
import { alignHeaders, addClassesToRows } from "./hooksCallbacks";

const hotOptions = {
  data,
  height: 464,
  colWidths: [140, 165, 100, 100, 100, 90, 90, 110, 178],
  colHeaders: [
    "Company name",
    "Product name",
    "Sell date",
    "In stock",
    "Qty",
    "Progress",
    "Rating",
    "Order ID",
    "Country",
  ],
  dropdownMenu: true,
  hiddenColumns: {
    indicators: true,
  },
  multiColumnSorting: true,
  filters: true,
  rowHeaders: true,
  manualRowMove: true,
  nestedRows: true,
  afterGetColHeader: alignHeaders,
  beforeRenderer: addClassesToRows,
  licenseKey: "non-commercial-and-evaluation",
};

export interface ToggleableOptions {
  disableTabNavigation: boolean;
  navigableHeaders: boolean;
  renderAllRows: boolean;
  enterBeginsEditing: boolean;
  autoWrapRow: boolean;
  autoWrapCol: boolean;
  enterMoves: { col: number; row: number };
}

function App() {
  const [toggleableOptions, setToggleableOptions] = useState<ToggleableOptions>(
    {
      disableTabNavigation: false,
      navigableHeaders: true,
      renderAllRows: false,
      enterBeginsEditing: true,
      autoWrapRow: true,
      autoWrapCol: true,
      enterMoves: { col: 0, row: 1 },
    }
  );

  return (
    <>
      <DemoOptions
        changeToggleOptions={setToggleableOptions}
        {...toggleableOptions}
      />
      <input
        className="placeholder-input"
        type="text"
        placeholder="Focusable text input"
      />
      <HotTable
        // allows us to re-render on virtualization change
        key={String(toggleableOptions.renderAllRows)}
        {...hotOptions}
        {...toggleableOptions}
      >
        <HotColumn data="companyName" type="text" />
        <HotColumn data="productName" type="text" />
        <HotColumn data="sellDate" type="date" allowInvalid={false} />
        <HotColumn data="inStock" type="checkbox" className="htCenter" />
        <HotColumn data="qty" type="numeric" />
        <HotColumn data="progress" readOnly={true} className="htMiddle">
          <ProgressBarRenderer hot-renderer />
        </HotColumn>
        <HotColumn data="rating" readOnly={true} className="htCenter">
          <StarsRenderer hot-renderer />
        </HotColumn>
        <HotColumn data="orderId" type="text" />
        <HotColumn data="country" type="dropdown" source={countries} />
      </HotTable>
      <input
        className="placeholder-input"
        type="text"
        placeholder="Focusable text input"
      />
    </>
  );
}

export default App;

// examples/next/docs/angular-wrapper/demo/src/app/app.component.ts
import { HotTableModule, GridSettings } from "@handsontable/angular-wrapper";
import { Component } from "@angular/core";
import { data } from "./constants";
import { PredefinedMenuItemKey } from "handsontable/plugins/contextMenu";
import { addClassesToRows } from "./utils/add-classes-to-rows.function";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.scss",
  standalone: true,
  imports: [HotTableModule],
})
export class AppComponent {
  readonly initialData = data;
  readonly gridSettings: GridSettings = {
    height: 450,
    colWidths: [180, 220, 140, 120, 120, 120, 140],
    colHeaders: [
      "Company Name",
      "Name",
      "Sell date",
      "In stock",
      "Quantity",
      "Order ID",
      "Country",
    ],
    contextMenu: [
      "cut",
      "copy",
      "---------",
      "row_above",
      "row_below",
      "remove_row",
      "---------",
      "alignment",
      "make_read_only",
      "clear_column",
    ] as PredefinedMenuItemKey[],
    dropdownMenu: true,
    hiddenColumns: {
      indicators: true,
    },
    multiColumnSorting: true,
    filters: true,
    rowHeaders: true,
    headerClassName: "htLeft",
    beforeRenderer: addClassesToRows,
    manualRowMove: true,
    autoWrapRow: true,
    autoWrapCol: true,
    autoRowSize: true,
    manualRowResize: true,
    manualColumnResize: true,
    navigableHeaders: true,
    imeFastEdit: true,
    columns: [
      { data: 1 },
      { data: 3 },
      { data: 4, type: "date", allowInvalid: false },
      { data: 6, type: "checkbox", className: "htCenter" },
      { data: 7, type: "numeric" },
      { data: 5 },
      { data: 2 },
    ],
  };
}

<div>
  <hot-table [data]="initialData" [settings]="gridSettings"></hot-table>
</div>
