// examples/next/visual-tests/react/demo/src/DataGrid.tsx
import "./styles.css";
import { HotTable, HotColumn } from "@handsontable/react";
import { data } from "./constants";
import { getThemeName } from "./utils";
import { ProgressBarRenderer } from "./renderers/ProgressBar";
import { StarsRenderer } from "./renderers/Stars";

import {
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "./hooksCallbacks";

const DataGrid = () => {
  const isRtl = document.documentElement.getAttribute("dir") === "rtl";

  return (
    <HotTable
      data={data}
      themeName={getThemeName()}
      height={450}
      colWidths={[140, 210, 135, 100, 90, 110, 120, 115, 140]}
      colHeaders={[
        "Company name",
        "Name",
        "Sell date",
        "In stock",
        "Qty",
        "Progress",
        "Rating",
        "Order ID",
        "Country"
      ]}
      dropdownMenu={true}
      hiddenColumns={{
        indicators: true
      }}
      contextMenu={true}
      multiColumnSorting={true}
      filters={true}
      rowHeaders={true}
      headerClassName={isRtl ? "htRight" : "htLeft"}
      beforeRenderer={addClassesToRows}
      afterGetRowHeader={drawCheckboxInRowHeaders}
      afterOnCellMouseDown={changeCheckboxCell}
      mergeCells={true}
      manualRowMove={true}
      navigableHeaders={true}
      comments={true}
      manualColumnMove={true}
      customBorders={true}
      licenseKey="non-commercial-and-evaluation"
    >
      <HotColumn data={1} />
      <HotColumn data={3} />
      <HotColumn data={4} type="date" allowInvalid={false} />
      <HotColumn data={6} type="checkbox" className="htCenter" headerClassName="htCenter" />
      <HotColumn data={7} type="numeric" headerClassName="htRight" />
      <HotColumn data={8} readOnly={true} className="htMiddle">
        <ProgressBarRenderer hot-renderer />
      </HotColumn>
      <HotColumn data={9} readOnly={true} className="htCenter" headerClassName="htCenter">
        <StarsRenderer hot-renderer />
      </HotColumn>
      <HotColumn data={5} />
      <HotColumn data={2} />
    </HotTable>
  );
}

export default DataGrid;

// examples/next/visual-tests/angular/demo/src/data-grid/data-grid.component.ts
import { Component, ViewEncapsulation } from "@angular/core";
import { getData } from "./utils/constants";
import { starsRenderer } from "./renderers/stars";
import { progressBarRenderer } from "./renderers/progressBar";

import {
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "./utils/hooks-callbacks";

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: "data-grid",
  templateUrl: "./data-grid.component.html",
  styleUrls: ["./data-grid.scss"]
})
export class DataGridComponent {
  dataset = getData();
  drawCheckboxInRowHeaders = drawCheckboxInRowHeaders;
  addClassesToRows = addClassesToRows;
  changeCheckboxCell = changeCheckboxCell;
  progressBarRenderer = progressBarRenderer;
  starsRenderer = starsRenderer;
  colHeaders = [
    "Company name",
    "Name",
    "Sell date",
    "In stock",
    "Qty",
    "Progress",
    "Rating",
    "Order ID",
    "Country"
  ];
  hiddenColumns = {
    indicators: true
  };
  headerClassNameValue = document.documentElement.getAttribute('dir') === 'rtl' ? 'htRight' : 'htLeft';
  licenseKey = "non-commercial-and-evaluation";
}

<div>
  <hot-table
    class="hot"
    id="root"
    [data]="dataset"
    height="450"
    [colWidths]="[140, 210, 135, 100, 90, 110, 120, 115, 140]"
    [colHeaders]="colHeaders"
    [rowHeaders]="true"
    [dropdownMenu]="true"
    [hiddenColumns]="hiddenColumns"
    [contextMenu]="true"
    [mergeCells]="true"
    [multiColumnSorting]="true"
    [filters]="true"
    [afterOnCellMouseDown]="changeCheckboxCell"
    [headerClassName]="headerClassNameValue"
    [afterGetRowHeader]="drawCheckboxInRowHeaders"
    [beforeRenderer]="addClassesToRows"
    [manualRowMove]="true"
    [navigableHeaders]="true"
    [comments]="true"
    [manualColumnMove]="true"
    [customBorders]="true"
    [themeName]="themeName"
    licenseKey="non-commercial-and-evaluation"
  >
    <hot-column data="1"></hot-column>
    <hot-column data="3"></hot-column>
    <hot-column data="4" type="date" [allowInvalid]="false"></hot-column>
    <hot-column data="6" type="checkbox" className="htCenter" headerClassName="htCenter"></hot-column>
    <hot-column data="7" type="numeric" headerClassName="htRight"></hot-column>
    <hot-column
      data="8"
      [renderer]="progressBarRenderer"
      [readOnly]="true"
      className="htMiddle"
    ></hot-column>
    <hot-column
      data="9"
      [renderer]="starsRenderer"
      [readOnly]="true"
      className="star htCenter"
      headerClassName="htCenter"
    ></hot-column>
    <hot-column data="5"></hot-column>
    <hot-column data="2"></hot-column>
  </hot-table>
</div>
