// docs/content/guides/accessories-and-menus/export-to-excel/react/example3.jsx
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';
import ExcelJS from 'exceljs';

registerAllModules();

const hotData = [
  ['Alice Martin', 'North', 142000, true],
  ['Bob Chen', 'East', 98500, true],
  ['Carol Davies', 'South', 76200, false],
  ['David Kim', 'West', 115300, true],
  ['Eva Rossi', 'North', 54800, false],
];

const ExampleComponent = () => (
  <>
    <div className="example-controls-container">
      <p>Right-click any cell to open the context menu.</p>
    </div>
    <HotTable
      data={hotData}
      columns={[
        { type: 'text' },
        { type: 'dropdown', source: ['North', 'South', 'East', 'West'] },
        {
          type: 'numeric',
          locale: 'en-US',
          numericFormat: { style: 'currency', currency: 'USD', minimumFractionDigits: 2 },
        },
        { type: 'checkbox' },
      ]}
      colHeaders={['Name', 'Region', 'Revenue ($)', 'Hit Target?']}
      rowHeaders={true}
      height="auto"
      autoWrapRow={true}
      autoWrapCol={true}
      contextMenu={true}
      exportFile={{ engines: { xlsx: ExcelJS } }}
      licenseKey="non-commercial-and-evaluation"
    />
  </>
);

export default ExampleComponent;

// docs/content/guides/accessories-and-menus/export-to-excel/vue/example3.vue
<script setup lang="ts">
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import ExcelJS from 'exceljs';
import type { GridSettings } from 'handsontable/settings';

registerAllModules();

const hotSettings = ref<GridSettings>({
  data: [
    ['Laptop Pro 15"', 'Electronics', 1299.99, 38, true],
    ['Wireless Mouse', 'Accessories', 29.99, 214, true],
    ['USB-C Hub 7-in-1', 'Accessories', 49.99, 87, true],
    ['Monitor 27" 4K', 'Electronics', 449.99, 12, false],
    ['Mech Keyboard', 'Accessories', 119.99, 65, true],
  ],
  columns: [
    { type: 'text' },
    { type: 'dropdown', source: ['Electronics', 'Accessories', 'Software'] },
    {
      type: 'numeric',
      locale: 'en-US',
      numericFormat: { style: 'currency', currency: 'USD', minimumFractionDigits: 2 },
    },
    { type: 'numeric' },
    { type: 'checkbox' },
  ],
  colHeaders: ['Product', 'Category', 'Unit Price', 'Stock', 'Active?'],
  rowHeaders: true,
  height: 'auto',
  autoWrapRow: true,
  autoWrapCol: true,
  contextMenu: true,
  exportFile: { engines: { xlsx: ExcelJS } },
  licenseKey: 'non-commercial-and-evaluation',
});
</script>

<template>
  <div id="example3">
    <div class="example-controls-container">
      <p>Right-click any cell to open the context menu.</p>
    </div>
    <HotTable :settings="hotSettings" />
  </div>
</template>
