// docs/content/guides/cell-features/read-only-cells/vue/exampleReadOnlyGrid.vue
<script setup lang="ts">
import { ref } from 'vue';
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';

registerAllModules();

const hotSettings = ref<GridSettings>({
  data: [
    { car: 'Tesla', year: 2017, chassis: 'black', bumper: 'black' },
    { car: 'Nissan', year: 2018, chassis: 'blue', bumper: 'blue' },
    { car: 'Chrysler', year: 2019, chassis: 'yellow', bumper: 'black' },
    { car: 'Volvo', year: 2020, chassis: 'white', bumper: 'gray' },
  ],
  height: 'auto',
  colHeaders: ['Car', 'Year', 'Chassis color', 'Bumper color'],
  licenseKey: 'non-commercial-and-evaluation',
  readOnly: true,
  autoWrapRow: true,
  autoWrapCol: true,
});
</script>

<template>
  <div id="exampleReadOnlyGrid">
    <HotTable :settings="hotSettings" />
  </div>
</template>

// docs/content/guides/cell-features/read-only-cells/react/exampleReadOnlyGrid.tsx
import { HotTable } from '@handsontable/react-wrapper';
import { registerAllModules } from 'handsontable/registry';

// register Handsontable's modules
registerAllModules();

const data = [
  { car: 'Tesla', year: 2017, chassis: 'black', bumper: 'black' },
  { car: 'Nissan', year: 2018, chassis: 'blue', bumper: 'blue' },
  { car: 'Chrysler', year: 2019, chassis: 'yellow', bumper: 'black' },
  { car: 'Volvo', year: 2020, chassis: 'white', bumper: 'gray' },
];

const ExampleComponent = () => {
  return (
    <HotTable
      data={data}
      height="auto"
      colHeaders={['Car', 'Year', 'Chassis color', 'Bumper color']}
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation"
      readOnly={true}
    />
  );
};

export default ExampleComponent;
