// docs/content/guides/cell-features/read-only-cells/vue/example4.vue
<script setup lang="ts">
import { HotTable } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import type { GridSettings } from 'handsontable/settings';

registerAllModules();

type CarRow = {
  car: string;
  year: number;
  chassis: string;
  bumper: string;
};

const data: CarRow[] = [
  { car: 'Tesla', year: 2017, chassis: 'black', bumper: 'black' },
  { car: 'Nissan', year: 2018, chassis: 'blue', bumper: 'blue' },
  { car: 'Chrysler', year: 2019, chassis: 'yellow', bumper: 'black' },
  { car: 'Volvo', year: 2020, chassis: 'white', bumper: 'gray' },
];

const hotSettings: GridSettings = {
  data,
  colHeaders: ['Car', 'Year', 'Chassis color', 'Bumper color'],
  height: 'auto',
  autoWrapRow: true,
  autoWrapCol: true,
  licenseKey: 'non-commercial-and-evaluation',
  cells(row, _col, prop) {
    const propName = prop as keyof CarRow;

    if (data[row]?.[propName] === 'Nissan') {
      return { editor: false };
    }

    return { editor: 'text' };
  },
};
</script>

<template>
  <div id="example4">
    <HotTable :settings="hotSettings" />
  </div>
</template>

// docs/content/guides/cell-features/disabled-cells/angular/example4.js
/* file: app.component.ts */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { GridSettings, HotTableComponent } from '@handsontable/angular-wrapper';

@Component({
  selector: 'example4-disabled-cells',
  standalone: false,
  template: ` <div>
    <hot-table [data]="data" [settings]="gridSettings"></hot-table>
  </div>`,
})
export class Example4DisabledCellsComponent implements AfterViewInit {
  @ViewChild(HotTableComponent, { static: false }) readonly hotTable!: HotTableComponent;

  readonly data = [
    { car: 'Tesla', year: 2017, chassis: 'black', bumper: 'black' },
    { car: 'Nissan', year: 2018, chassis: 'blue', bumper: 'blue' },
    { car: 'Chrysler', year: 2019, chassis: 'yellow', bumper: 'black' },
    { car: 'Volvo', year: 2020, chassis: 'white', bumper: 'gray' },
  ];

  readonly gridSettings: GridSettings = {
    height: 'auto',
    colHeaders: ['Car', 'Year', 'Chassis color', 'Bumper color'],
    autoWrapRow: true,
    autoWrapCol: true
  };

  ngAfterViewInit(): void {
    const hot = this.hotTable?.hotInstance;

    hot?.updateSettings({
      cells: (row, _col, prop) => {
        if (hot.getDataAtRowProp(row, prop as string) === 'Nissan') {
          return { editor: false };
        }
        return { editor: 'text' };
      },
    });
  }
}
/* end-file */


/* file: app.module.ts */
import { NgModule, ApplicationConfig } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { registerAllModules } from 'handsontable/registry';
import { HOT_GLOBAL_CONFIG, HotConfig, HotTableModule } from '@handsontable/angular-wrapper';
import { CommonModule } from '@angular/common';
import { NON_COMMERCIAL_LICENSE } from '@handsontable/angular-wrapper';

/* start:skip-in-compilation */
import { Example4DisabledCellsComponent } from './app.component';
/* end:skip-in-compilation */

// register Handsontable's modules
registerAllModules();

export const appConfig: ApplicationConfig = {
  providers: [
    {
      provide: HOT_GLOBAL_CONFIG,
      useValue: {
        themeName: 'ht-theme-main',
        license: NON_COMMERCIAL_LICENSE,
      } as HotConfig
    }
  ],
};

@NgModule({
  imports: [ BrowserModule, HotTableModule, CommonModule ],
  declarations: [ Example4DisabledCellsComponent ],
  providers: [...appConfig.providers],
  bootstrap: [ Example4DisabledCellsComponent ]
})

export class AppModule { }
/* end-file */
