// examples/next/visual-tests/react-wrapper/demo/src/DataGrid.tsx
import "./styles.css";
import { HotTable, HotColumn } from "@handsontable/react-wrapper";
import { data } from "./constants";
import { getThemeName } from "./utils";
import { ProgressBarRenderer } from "./renderers/ProgressBar";
import { StarsRenderer } from "./renderers/Stars";

import {
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "./hooksCallbacks";

const DataGrid = () => {
  const isRtl = document.documentElement.getAttribute('dir') === 'rtl';

  return (
    <HotTable
      data={data}
      themeName={getThemeName()}
      height={450}
      colWidths={[140, 210, 135, 100, 90, 110, 120, 115, 140]}
      colHeaders={[
        "Company name",
        "Name",
        "Sell date",
        "In stock",
        "Qty",
        "Progress",
        "Rating",
        "Order ID",
        "Country"
      ]}
      dropdownMenu={true}
      hiddenColumns={{
        indicators: true
      }}
      contextMenu={true}
      multiColumnSorting={true}
      filters={true}
      rowHeaders={true}
      headerClassName={isRtl ? "htRight" : "htLeft"}
      beforeRenderer={addClassesToRows}
      afterGetRowHeader={drawCheckboxInRowHeaders}
      afterOnCellMouseDown={changeCheckboxCell}
      mergeCells={true}
      manualRowMove={true}
      navigableHeaders={true}
      comments={true}
      manualColumnMove={true}
      customBorders={true}
      licenseKey="non-commercial-and-evaluation"
    >
      <HotColumn data={1} />
      <HotColumn data={3} />
      <HotColumn data={4} type="date" allowInvalid={false} />
      <HotColumn data={6} type="checkbox" className="htCenter" headerClassName="htCenter" />
      <HotColumn data={7} type="numeric" headerClassName="htRight" />
      <HotColumn data={8} readOnly={true} className="htMiddle" renderer={ProgressBarRenderer}/>
      <HotColumn data={9} readOnly={true} className="htCenter" headerClassName="htCenter" renderer={StarsRenderer} />
      <HotColumn data={5} />
      <HotColumn data={2} />
    </HotTable>
  );
}

export default DataGrid;

// examples/next/visual-tests/vue3/demo/src/components/DataGrid.vue
<template>
  <hot-table ref="hotTableComponent" :data="data" :settings="hotSettings"></hot-table>
</template>

<script lang="ts">
import { HotTable } from '@handsontable/vue3';
import { getData } from "../utils/constants";
import { getThemeName } from "../utils/utils";
import { progressBarRenderer } from "../renderers/progressBar";
import { starsRenderer } from "../renderers/stars";

import {
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "../utils/hooks-callbacks";

export default {
  name: 'DataGrid',
  data: function() {
    const isRtl = document.documentElement.getAttribute('dir') === 'rtl';

    return {
      hotSettings: {
        themeName: getThemeName(),
        height: 450,
        dropdownMenu: true,
        manualRowMove: true,
        hiddenColumns: {
          indicators: true,
        },
        contextMenu: true,
        mergeCells: true,
        multiColumnSorting: true,
        filters: true,
        rowHeaders: true,
        navigableHeaders: true,
        manualColumnMove: true,
        comments: true,
        customBorders: true,
        afterOnCellMouseDown: changeCheckboxCell,
        headerClassName: isRtl ? "htRight" : "htLeft",
        afterGetRowHeader: drawCheckboxInRowHeaders,
        beforeRenderer: addClassesToRows,
        colWidths: [140, 210, 135, 100, 90, 110, 120, 115, 140],
        colHeaders: [
          "Company name",
          "Name",
          "Sell date",
          "In stock",
          "Qty",
          "Progress",
          "Rating",
          "Order ID",
          "Country"
        ],
        columns: [
          { data: 1, type: "text" },
          { data: 3, type: "text" },
          {
            data: 4,
            type: "date",
            allowInvalid: false
          },
          {
            data: 6,
            type: "checkbox",
            className: "htCenter",
            headerClassName: "htCenter"
          },
          {
            data: 7,
            type: "numeric",
            headerClassName: "htRight"
          },
          {
            data: 8,
            renderer: progressBarRenderer,
            readOnly: true,
            className: "htMiddle"
          },
          {
            data: 9,
            renderer: starsRenderer,
            readOnly: true,
            className: "star htCenter",
            headerClassName: "htCenter",
          },
          { data: 5, type: "text" },
          { data: 2, type: "text" }
        ],
        licenseKey: "non-commercial-and-evaluation",
      },
      data: getData()
    }
  },
  components: {
    HotTable
  }
}
</script>

<style lang="scss">
  .handsontable .progressBar {
    background: #37bc6c !important;
    height: 10px;
  }

  .handsontable .star {
    color: #fcb515 !important;
  }

  .ht-wrapper .handsontable .htCore tr.selected td {
    background: #edf3fd !important;
  }

  .handsontable .ht_nestingParent,
  .handsontable .ht_nestingParent ~ td {
    background: #B5B5B5 !important;
    color: #222 !important;
  }
</style>
