// examples/next/visual-tests/angular/demo/src/scenario-grid/scenario-grid.component.ts
import { Component, ViewEncapsulation } from "@angular/core";
import { getScenarioData } from "./utils/constants";
import { starsRenderer } from "./renderers/stars";
import { progressBarRenderer } from "./renderers/progressBar";

import {
  alignHeaders,
  drawCheckboxInRowHeaders,
  addClassesToRows,
  changeCheckboxCell
} from "./utils/hooks-callbacks";

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: "scenario-grid",
  templateUrl: "./scenario-grid.component.html",
  styleUrls: ["./scenario-grid.scss"]
})
export class ScenarioGridComponent {
  dataset = getScenarioData();
  alignHeaders = alignHeaders;
  drawCheckboxInRowHeaders = drawCheckboxInRowHeaders;
  addClassesToRows = addClassesToRows;
  changeCheckboxCell = changeCheckboxCell;
  progressBarRenderer = progressBarRenderer;
  starsRenderer = starsRenderer;
  colHeaders = [
    'Product ID',
    'Mobile Apps',
    'Pricing',
    'Rating',
    'Category',
    'Industry',
    'Business Scale',
    'User Type',
    'No of Users',
    'Deployment',
    'OS'
  ];
  hiddenColumns = {
    indicators: true
  };
  licenseKey = "non-commercial-and-evaluation";
}

<div>
  <hot-table
    class="hot"
    id="root"
    [data]="dataset"
    height="250"
    [afterGetColHeader]="alignHeaders"
    [colHeaders]="colHeaders"
    [rowHeaders]="true"
    [dropdownMenu]="true"
    [hiddenColumns]="hiddenColumns"
    [contextMenu]="true"
    [mergeCells]="true"
    [multiColumnSorting]="true"
    [filters]="true"
    [afterOnCellMouseDown]="changeCheckboxCell"
    [afterGetColHeader]="alignHeaders"
    [afterGetRowHeader]="drawCheckboxInRowHeaders"
    [beforeRenderer]="addClassesToRows"
    [manualRowMove]="true"
    [navigableHeaders]="true"
    [comments]="true"
    [manualColumnMove]="true"
    [customBorders]="true"
    [autoWrapCol]="true"
    [autoWrapRow]="true"
    licenseKey="non-commercial-and-evaluation"
  >
    <hot-column data="1" type="numeric"></hot-column>
    <hot-column data="2"></hot-column>
    <hot-column data="3"></hot-column>
    <hot-column data="4" type="numeric"></hot-column>
    <hot-column data="5"></hot-column>
    <hot-column data="6"></hot-column>
    <hot-column data="7"></hot-column>
    <hot-column data="8"></hot-column>
    <hot-column data="9"></hot-column>
    <hot-column data="10"></hot-column>

   
  </hot-table>
</div>

// examples/next/visual-tests/vue3/demo/src/components/ScenarioGrid.vue
<template>
  <div>
    <div id='tableTop'>

      <input type="text" class="input-spacing" placeholder="Input 1" />
      <hot-table ref="hotTableComponent1" :data="dataTop" :settings="hotSettings1"></hot-table>
    </div>
    <div id='tableBottom'>
      <input type="text" class="input-spacing" placeholder="Input 2" />
      <hot-table ref="hotTableComponent2" :data="dataBottom" :settings="hotSettings2"></hot-table>
    </div>
  </div>
</template>

<script lang="ts">
import { HotTable } from '@handsontable/vue';
import { scenarioDataTop, scenarioDataBottom } from '../utils/constants';
import { getThemeName } from "../utils/utils";

export default {
  name: 'ScenarioGrid',
  data: function () {
    return {
      dataTop: scenarioDataTop,
      dataBottom: scenarioDataBottom,
      hotSettings1: {
        themeName: getThemeName(),
        height: 350,
        dropdownMenu: true,
        manualRowMove: true,
        hiddenColumns: {
          indicators: true,
        },
        contextMenu: true,
        mergeCells: true,
        multiColumnSorting: true,
        filters: true,
        rowHeaders: true,
        navigableHeaders: true,
        manualColumnMove: true,
        comments: true,
        customBorders: true,
        fixedRowsBottom: 2,
        colHeaders: true,
        nestedHeaders: [
          [
            { label: 'Product', colspan: 4 },
            { label: 'Category', colspan: 3 },
            { label: 'User', colspan: 2 },
            { label: 'System', colspan: 2 },
          ],
          [
            'Product ID',
            'Mobile Apps',
            'Pricing',
            'Rating',
            'Data Type',
            'Industry',
            'Business Scale',
            'User Type',
            'No of Users',
            'Deployment',
            'OS',
          ],
        ],
        columns: [
          { data: 'product_id', type: 'numeric' },
          { data: 'mobile_apps', type: 'text' },
          { data: 'pricing', type: 'text' },
          { data: 'rating', type: 'numeric' },
          { data: 'category', type: 'text' },
          { data: 'industry', type: 'text' },
          { data: 'business_scale', type: 'text' },
          { data: 'user_type', type: 'text' },
          { data: 'no_of_users', type: 'text' },
          { data: 'deployment', type: 'text' },
          { data: 'OS', type: 'text' },
        ],
        collapsibleColumns: true,
        licenseKey: 'non-commercial-and-evaluation',
      },
      hotSettings2: {
        themeName: getThemeName(),
        height: 250,
        dropdownMenu: true,
        manualRowMove: true,
        hiddenColumns: {
          indicators: true,
        },
        contextMenu: true,
        mergeCells: true,
        multiColumnSorting: true,
        filters: true,
        rowHeaders: true,
        navigableHeaders: true,
        manualColumnMove: true,
        comments: true,
        customBorders: true,
        nestedRows: true,
        bindRowsWithHeaders: true,
        colHeaders: [
          'Category',
          'Product ID',
          'Industry',
          'Business Scale',
          'User Type',
          'No of Users',
          'Deployment',
          'OS',
          'Mobile Apps',
          'Pricing',
          'Rating',
        ],
        columnSummary: [
          {
            sourceColumn: 10,
            type: 'average',
            destinationRow: 0,
            destinationColumn: 10,
            // force this column summary to treat non-numeric values as numeric values
            forceNumeric: true
          },
        ],
        columns: [
          { data: 'category', type: 'text' },
          { data: 'product_id', type: 'numeric' },
          { data: 'industry', type: 'text' },
          { data: 'business_scale', type: 'text' },
          { data: 'user_type', type: 'text' },
          { data: 'no_of_users', type: 'text' },
          { data: 'deployment', type: 'text' },
          { data: 'OS', type: 'text' },
          { data: 'mobile_apps', type: 'text' },
          { data: 'pricing', type: 'text' },
          { data: 'rating', type: 'numeric' },
        ],
        licenseKey: 'non-commercial-and-evaluation',
      },
    };
  },
  components: {
    HotTable,
  },
};
</script>

<style lang="scss">
  .handsontable td .progressBar {
    background: #37bc6c !important;
    height: 10px;
  }

  .handsontable td.star {
    color: #fcb515 !important;
  }

  .ht-wrapper .handsontable .htCore tr.selected td {
    background: #edf3fd !important;
  }
</style>
